import "../styles/globals.css";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import store from "../store/store"
import { ClerkProvider } from "@clerk/nextjs";
import { Provider } from "react-redux";
import UserProvider from "../context";
import favIcon from "../public/favicon.ico"

export default function App({ Component, pageProps }) {
  return (
    <>

      <Head>
        <title>Online Shoe Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, intial-scale=1" />
        <link rel="icon" type="image/x-icon" href="../public/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <ClerkProvider {...pageProps}>
      <UserProvider>
        <Provider store={store}>
          <Header />
          <Component {...pageProps} />
          <Footer />
        </Provider>
      </UserProvider>
      </ClerkProvider>
    </>
  );
}
